### ISSUE TITLE
Version 0.0.0?

### ISSUE THREAD

**Issue by p4bloch** [Mango/mango-node#4]
Is there a reason for this package to be 0.0.0? I'm wrapping it for Meteor and want to keep the same semver as this package. I see there's a 0.0.1 tag, but it doesn't seem to be taken into account by [npm](https://www.npmjs.com/package/mango)

PS: Saturday night insomnia :)

**Comment by danzajdband** [comment]
It was tricky due to previously versions issues. Now there is a 0.0.3 version on npm.
